### ISSUE TITLE
Suggested enhancements part 2

### ISSUE THREAD

**Issue by Belzedar94** [ianfab/chess-variant-puzzler#11]
As the project is starting to drag some interest, I'm opening this thread to compile a few suggestions to inspire future development:

- [ ] Remove puzzles that share the same solution (to avoid slight variations that lead to the same exact solution as chapters 2-3 of https://lichess.org/study/vxrJlFCV).
- [ ] Add a concurrency option on the generator so games can be generated in paralel when more than 1 thread is available.
- [ ] Add the posibility to filter mates in X (using for example the Eval printed in the epd, e.g.: Eval=# 2)

**Comment by ianfab** [comment]
Thanks, these suggestions make sense. May I ask you to split them into separate issues?

**Comment by Belzedar94** [comment]
> * Add the posibility to filter mates in X (using for example the Eval printed in the epd, e.g.: Eval=# 2)

Done!

**Comment by ianfab** [comment]
Thanks
