### ISSUE TITLE
Force all-the-way-through solutions where there is an announced mate

### ISSUE THREAD

**Issue by Belzedar94** [ianfab/chess-variant-puzzler#17]
When working only with mates, a lot of times the proposed solution doesn't cover the whole mate sequence. It would be nice to force the puzzler to annotate the whole solution when there is an announced mate.

An example:

[Crazyhouse] - In this case, only B@f8 is printed, while the desired solution would be (shortest forced mate): B@f8+, Ke6, exf5+, Kxf5, Ng3+, Ke6, B@d5+, Ke5, d4#
`3r4/p1p1kpQp/3p1N1p/5bbN/4P3/3PP3/PPq2nPP/r3BK1R[Brnppp] w - - 4 39;variant crazyhouse;bm B@f8;eval #5;difficulty 6;quality 1.00;type mate;pv B@f8`

**Comment by ianfab** [comment]
The reason for that is that the puzzle algorithm is applied recursively. On every position of the line it checks whether the solution still is unique, and if not it stops. This ensure that all puzzles are sound. Handing alternative solutions would complicate matters.
