### ISSUE TITLE
multiple mating sequence from puzzles generated from puzzler

### ISSUE THREAD

**Issue by NelloHo** [ianfab/chess-variant-puzzler#30]
take a look at this xiangqi fen generated by puzzler.py:
`
2b1k4/1CNN5/9/9/2bPPn3/9/P8/4B4/4A4/2BAK4 w - - 0
`
it has multiple mating sequence(#3) :
![image](https://user-images.githubusercontent.com/99171663/196712760-89331531-3c2e-4308-a1e9-fb8f1a62c269.png)

puzzler.py will kick out puzzles with multiple mating sequence iirc
don't know why this happend

**Comment by ianfab** [comment]
Please provide more context, like the settings used and the EPD output line it generated.

**Comment by NelloHo** [comment]
thanks
the param I use:
`
python3 puzzler.py --engine fairy-stockfish --variant xiangqi -d 12 -r 1.5 fens.epd
`
the result:
`
2b1k4/1CNN5/9/9/2bPPn3/9/P8/4B4/4A4/2BAK4 w - - 0;variant xiangqi;bm d9e7;eval #3;difficulty 0.054;content 4.668;quality 0.018;volatility 0.008;volatility2 0.008;accuracy 0.024;accuracy2 0.040;std 0.000;ambiguity 0.600;type mate;pv d9e7,e10f10,e6f6,c6a8,e7g8
`

**Comment by NelloHo** [comment]
It may sound redundant, but may I ask you 
1. this is a `#3` puzzle , why would we need `depth 15` to check out whether it has a unique pv?
2. what does `side depth` mean ? why can't we parse it in puzzler.py ?

**Comment by ianfab** [comment]
1. (Fairy-)SF does forward pruning, so one can't guarantee anything regarding at which depth a node will be found.
2. No clue.

**Comment by NelloHo** [comment]
thank you !
